### ISSUE TITLE
Border and Font Display Issues on Signup and Login Pages

### ISSUE THREAD

**Issue by Nabin-kharel1999** [avimanyurimal/Collaborative-Development-HMS-Project#32]
Description:
Users are experiencing inconsistencies with border styles and font display on the signup and login pages. The borders around input fields appear uneven, and there are discrepancies in font styles between different sections of the pages. This affects the overall user experience and visual consistency of the application.
Steps to Reproduce:
Observe the border styles around input fields such as username, email, and password.
Notice any differences in border styles and font display compared to the signup page.
Expected Behavior:
Borders around input fields should have consistent styling throughout the signup and login pages. Additionally, font styles should remain uniform across all sections for a cohesive visual appearance.
Actual Behavior:
Border styles around input fields vary in thickness and color, leading to an uneven visual presentation. Moreover, font styles differ between sections, causing inconsistency in the overall design.

**Comment by avimanyurimal** [comment]
I'm happy to announce that the inconsistencies with border styles and font display on the signup and login pages have been resolved. Changes ensure uniform border thickness and font styles across all sections. Tested thoroughly for consistency. Closing the issue now.
