### ISSUE TITLE
 Duplicate Rendering of NavBar and Footer

### ISSUE THREAD

**Issue by Nabin-kharel1999** [avimanyurimal/Collaborative-Development-HMS-Project#35]
Currently, our project is facing an issue where both the navbar and footer are being rendered twice on resident pages. This redundancy not only affects the performance of our application but also introduces unnecessary clutter in the DOM.

**Comment by samyog777** [comment]
It was showinf error because of the props in the navBar and footer. My teammates calls it using props recursively. I solved by removing one component call.
