### ISSUE TITLE
Potential bug in Resident Home component where meal data isn't fetched from backend. Need to add functionality to fetch meal data using an endpoint.

### ISSUE THREAD

**Issue by Nabin-kharel1999** [avimanyurimal/Collaborative-Development-HMS-Project#37]
Potential bug where meal data was not being fetched from the backend in the Resident Home component. Need some solution to resolve this issue by adding functionality to fetch meal data from the backend using an endpoint to retrieve meal data from respective tables in the backend.

**Comment by avimanyurimal** [comment]
Implemented a solution to resolve a potential bug where meal data was not being fetched from the backend in the ResidentHome component. Added functionality to fetch meal data from the backend by implementing an endpoint to retrieve meal data from respective tables.
