### ISSUE TITLE
User keeps getting logged out, and residency choice disappears when refreshing

### ISSUE THREAD

**Issue by Nabin-kharel1999** [avimanyurimal/Collaborative-Development-HMS-Project#38]
User keeps getting logged out, and residency choice disappears when refreshing. the local storage is not so working need to fix it need to show the login data user name in navbar after refreshing the page .

**Comment by avimanyurimal** [comment]
Fixed the problem where users were logged out and residency choice disappeared after refreshing by updating how we store and retrieve data
